#!/usr/bin/perl
###########################################
# release -- Release this module
# Mike Schilli, 2002 (m@perlmeister.com)
###########################################
use warnings;
use strict;

    # Available at http://perlmeister.com/scripts
use ModDevUtils;

{
    no strict;
    *ModDevUtils::main_pm_file = sub { "lib/Net/SSH/AuthorizedKeysFile.pm" };
}
ModDevUtils::release() or exit 0;
